version: 0.0
os: linux
files:
  - source: Assignment3_WebApp5/build_output
    destination: /home/ubuntu/assignment3_webapp5
  - source: scripts/virtualhost.conf
    destination: /home/ubuntu/assignment3_webapp5
hooks:
  ApplicationStop:
    - location: scripts/stop_service
    timeout: 300
    runas: root

  BeforeInstall:
    - location: scripts/remove_application
    timeout: 300
    runas: root

  AfterInstall:
    - location: scripts/install_dotnetcore
    timeout: 500
    runas: root

    - location: scripts/install_httpd
    timeout: 300
    runas: root

  ApplicationStart:
    - location: scripts/start_service
    timeout: 300
    runas: root